name: Tag

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get latest tag
        id: latest-tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT
          
      - name: Calculate next version
        id: next-version
        run: |
          LATEST_TAG=${{ steps.latest-tag.outputs.LATEST_TAG }}
          # Remove 'v' prefix if present
          VERSION=${LATEST_TAG#v}
          # Split version into parts
          IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"
          MAJOR=${VERSION_PARTS[0]:-0}
          MINOR=${VERSION_PARTS[1]:-0}
          PATCH=${VERSION_PARTS[2]:-0}
          # Increment patch version
          PATCH=$((PATCH + 1))
          NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
          
      - name: Create and push tag
        run: |
          NEW_VERSION=${{ steps.next-version.outputs.NEW_VERSION }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a $NEW_VERSION -m "Auto-generated tag $NEW_VERSION"
          git push origin $NEW_VERSION